### ISSUE TITLE
ds.copy_variable() throws a ClientError

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#234] opened 2018-01-19 22:49 UTC
This one is a bit odd because it does work sometimes, but most of the time this afternoon it is throwing the following

`ClientError: (<Response [400]>, 'https://app.crunch.io/api/datasets/.../variables/', {u'status': u'400 Bad Request', u'message': u'There was a problem with your derivation expression'})`

The error message there does not seem to describe what's actually going wrong, because this happens on derived and non-derived variables, arrays and non-arrays alike.

Example payload being sent by the method:

`{'body': {'alias': 'SQ7_test', 'name': 'SQ7_test', 'derivation': {'function': 'copy_variable', 'args': [{'variable': 'https://app.crunch.io/api/datasets/4f2ebd029ff2414191537eff6037099f/variables/000527/'}]}}, 'element': 'shoji:entity'}`

**Comment by mathiasbc** [comment] 2018-02-08 17:27
I was never able to reproduce this one. One thing is certain, the payload being sent it not wrong. So I'm gonna close this ticket since seems to be related to random errors in Crunch backend.

**Closed** 2018-02-08 17:27 UTC
