### ISSUE TITLE
ds.get_exclusion() returns Unknown function "selected"

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#346] opened 2019-02-05 17:28 UTC
You can see this on `5dc4500a31574f958cae1dceb637e685`.

```
<ipython-input-30-57503977d6f4> in <module>()
----> 1 ds.get_exclusion()

C:\ProgramData\Anaconda2\lib\site-packages\scrunch\scrunch\datasets.pyc in get_exclusion(self)
   2263             return None
   2264         expr = exclusion['body'].get('expression')
-> 2265         return prettify(expr, self) if expr else None
   2266 
   2267     def add_filter(self, name, expr, public=False):

C:\ProgramData\Anaconda2\lib\site-packages\scrunch\scrunch\expressions.pyc in prettify(expr, ds)
    791         return _transform(_func, args, nest=nest)
    792 
--> 793     return _process(_resolve_variables(expr))

C:\ProgramData\Anaconda2\lib\site-packages\scrunch\scrunch\expressions.pyc in _process(fragment, parent)
    778             return list(fragment.values())[0]
    779 
--> 780         args = [_process(arg, _func) for arg in fragment['args']]
    781         child_functions = [
    782             arg.get('function')

C:\ProgramData\Anaconda2\lib\site-packages\scrunch\scrunch\expressions.pyc in _process(fragment, parent)
    789             _func == 'or'
    790         )
--> 791         return _transform(_func, args, nest=nest)
    792 
    793     return _process(_resolve_variables(expr))

C:\ProgramData\Anaconda2\lib\site-packages\scrunch\scrunch\expressions.pyc in _transform(f, args, nest)
    747             result = '%s(%s)' % (functions[f], args[0])
    748         else:
--> 749             raise Exception('Unknown function "%s"' % f)
    750 
    751         if nest:

Exception: Unknown function "selected"
```

**Comment by xbito** [comment] 2019-02-06 19:54
It might be happening only in this particular dataset, or maybe with this particular kind of exclusion.

**Comment by mathiasbc** [comment] 2019-02-08 21:52
I pushed a fix for this in the branch: https://github.com/Crunch-io/scrunch/pull/338/files#diff-54e01706c90fd9d7e26c9f5f4d422b75R63

The problem is we had no support for selected, as the syntax was not clear to us how we were going to use it in Scrunch, but  just followed what we had for `not_selected` and made sure the expression prettifier properly converts the JSON to a string.

**Closed** 2019-07-10 21:23 UTC
Labels: bug
