### ISSUE TITLE
create_multitable drops transform object

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#248] opened 2018-03-23 14:46 UTC
The `transform` object during multitable creation is lost, resulting in the `transform` instructions being ignored. It looks like this is an indentation error:

```python
            if not processed:
                parsed_q = process_expr(parse_expr(q['query']), self.resource)
                # wrap the query in a list of one dict element
                as_json['query'] = [parsed_q]
                if 'transform' in q.keys():
                    as_json['transform'] = q['transform']
```

Should be (?):

```python
            if not processed:
                parsed_q = process_expr(parse_expr(q['query']), self.resource)
                # wrap the query in a list of one dict element
                as_json['query'] = [parsed_q]

            if 'transform' in q.keys():
                as_json['transform'] = q['transform']
```

This fixes the problem in the test I have run but not sure if there will be any collateral damage.

Currently, in an example like this:

```python
bann_name = 'Banner'
bann_vars = [
        {'query': 'gender'},
        {'query': 'age_rc2'},
        {
            'query': 'age_rc3',
            'transform': {
                'categories': [
                    {'id': 1},
                    {'id': 2},
                    {'id': 3},
                    {'id': 4, 'hide': True},
                ]
            }
        },
        {'query': 'geo_state_au_rc'},
]

banner1 =  ds.create_multitable(
    name=bann_name,
    template=bann_vars,
    is_public=True
)
```

The 4th category in `age_rc3` will not be hidden, because the whole `transform` object is ignored.

**Comment by mathiasbc** [comment] 2018-05-08 23:03
I can't remember the reason for having that indentation, anyway I think you are right and we should respect the `transform` element at any time, all tests pass and I was able to reproduce. Closing

**Closed by mathiasbc** 2018-05-08 23:03 UTC
